name: CD

on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Move compiled JAR file
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/SkyblockSandbox-1.0.jar
          remote: SkyblockSandbox/plugins/SkyblockSandbox-1.0.jar
          host: ${{ secrets.HOST }}
          port: 911
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Deploy Stage
          uses: fjogeleit/http-request-action@master
          with:
            url: ${{ secrets.APIURL }}
            method: 'GET'
